#include <stdio.h>
/**
* main - Each new term in the Fibonacci sequence is generated by
* adding the previous two terms. By starting with 1 and 2
* Fibonacci sequence values not exceed 4,000,000
*
* Return:0
*/
int main(void)
{
	int first, second, c, next;

	first = 1;
	second = 2;
	c = 2;

	next = first + second;
	while (next  < 4000000)
	{
		next = first + second;
		first = second;
		second = next;
		if (next % 2 == 0)
		{
			c = c + next;
		}
	}
	printf("%d", c);
	printf("\n");
	return (0);
}
